/**
 * Short, common English words that are easy to say on the phone and hard to mistype: 3 to 6
 * letters, no look-alike spellings, nothing that reads badly.
 */
export const TEMPORARY_PASSWORD_WORDS = [
  'apple',
  'river',
  'table',
  'green',
  'house',
  'water',
  'light',
  'bread',
  'chair',
  'cloud',
  'dream',
  'field',
  'flame',
  'fruit',
  'grape',
  'grass',
  'heart',
  'honey',
  'horse',
  'lemon',
  'mango',
  'maple',
  'melon',
  'money',
  'music',
  'night',
  'ocean',
  'olive',
  'paper',
  'peach',
  'pearl',
  'piano',
  'plant',
  'queen',
  'radio',
  'robin',
  'salad',
  'sheep',
  'shell',
  'smile',
  'snow',
  'spoon',
  'stone',
  'storm',
  'sugar',
  'sunny',
  'tiger',
  'toast',
  'tower',
  'train',
  'tulip',
  'violet',
  'whale',
  'wheat',
  'world',
  'yellow',
  'amber',
  'beach',
  'berry',
  'bird',
  'blue',
  'boat',
  'book',
  'brick',
  'cake',
  'camel',
  'candle',
  'cedar',
  'coffee',
  'coral',
  'cotton',
  'daisy',
  'desk',
  'dove',
  'eagle',
  'earth',
  'fern',
  'fish',
  'flower',
  'forest',
  'garden',
  'glass',
  'gold',
  'hill',
  'island',
  'jacket',
  'jungle',
  'kite',
  'lake',
  'leaf',
  'lily',
  'lion',
  'mint',
  'moon',
  'nest',
  'orange',
  'panda',
  'park',
  'pencil',
  'pepper',
  'pillow',
  'pine',
  'planet',
  'pond',
  'rain',
  'rice',
  'rose',
  'sand',
  'silver',
  'sky',
  'star',
  'summer',
  'sun',
  'swan',
  'tea',
  'tree',
  'valley',
  'wind',
  'winter',
  'wood',
] as const;

/**
 * A temporary password: one word and four digits, all lower case, such as river4827. `random(n)`
 * returns a whole number from 0 to n - 1; pass a cryptographically secure one.
 */
export function makeTemporaryPassword(random: (n: number) => number): string {
  const word =
    TEMPORARY_PASSWORD_WORDS[random(TEMPORARY_PASSWORD_WORDS.length)] ??
    'river';
  const digits = String(random(10_000)).padStart(4, '0');
  return `${word}${digits}`;
}

/** What a generated temporary password looks like. */
export const TEMPORARY_PASSWORD_PATTERN = /^[a-z]{3,6}\d{4}$/;
